name: Compile PDFs

on:
  workflow_dispatch:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Install Roboto font
      run: |
        apt-get update && apt-get install -y fonts-roboto

    - name: Compile
      run: make

    - uses: actions/upload-artifact@v4
      with:
        name: examples
        path: examples/*.pdf
